### ISSUE TITLE
Let language-lua compile with GHC 8.2

### ISSUE THREAD

**Issue by nikomi** [glguy/language-lua#1]
GHC 8.2 comes with base 4.10, so language-lua refuses to compile due to constraint base < 4.10.

Could you please lift the constraint to base < 5 to make language-lia compile with GHC 8.2?

Thanks, Nik

**Comment by glguy** [comment]
updated on Hackage.

**Comment by nikomi** [comment]
Thanks for the quick response!

**Comment by nikomi** [comment]
Sorry to bother you again - Hackage still does not seem to have that new version available.

**Comment by glguy** [comment]
I don't know what happened, I thought that I'd updated the metadata on hackage when I wrote that comment. It should be there now, however.

**Comment by nikomi** [comment]
Ah - now it says base < 4.11, thanks!
